name: Create Release Asset

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip source code excluding .git
      run: |
        zip -r OptimatraDE_Trading_Bot.zip . -x ".git/*" -x ".github/*"

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: OptimatraDE_Trading_Bot.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
